# YAML Linting Rules for YugabyteDB Project
# Configuration for yamllint to ensure consistent YAML formatting

extends: default

rules:
  # Line length can be longer for Kubernetes manifests
  line-length:
    max: 150
    level: warning

  # Allow longer comments for documentation
  comments:
    min-spaces-from-content: 1
    require-starting-space: true

  # Be more lenient with indentation for complex Kubernetes structures
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
    level: warning

  # Allow empty lines for readability
  empty-lines:
    max: 3
    max-start: 0
    max-end: 1

  # Allow truthy values common in Kubernetes
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

  # Allow long lines in comments for URLs and examples
  comments-indentation: disable

  # Allow document separators (---)
  document-start: disable

  # Allow multiple documents in one file
  document-end: disable

  # Allow empty values in Kubernetes manifests
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # Allow key duplicates in some cases (common in Kubernetes)
  key-duplicates: enable

  # Allow octal values (common in file permissions)
  octal-values:
    forbid-implicit-octal: false
    forbid-explicit-octal: false

  # Allow quoted strings
  quoted-strings:
    quote-type: any
    required: false

  # Allow braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Allow brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Allow colons
  colons:
    max-spaces-after: -1
    level: error

  # Allow commas
  commas:
    max-spaces-after: -1
    level: error

  # Allow hyphens
  hyphens:
    level: error

  # Allow new line at end of file
  new-line-at-end-of-file: disable

  # Allow trailing spaces
  trailing-spaces: disable

  # Allow key ordering
  key-ordering: disable

  # Be more lenient with line endings for cross-platform compatibility
  new-lines:
    type: unix
    level: warning

ignore: |
  .git/
  .github/
  node_modules/
  *.md
  credentials/ 