# YAML Linting Rules for YugabyteDB Project
# Configuration for yamllint to ensure consistent YAML formatting
# Updated for enhanced security and consistency

extends: default

rules:
  # Line length can be longer for Kubernetes manifests
  line-length:
    max: 150
    level: warning

  # Allow longer comments for documentation
  comments:
    min-spaces-from-content: 1
    require-starting-space: true

  # Be more lenient with indentation for complex Kubernetes structures
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
    level: warning

  # Allow empty lines for readability
  empty-lines:
    max: 3
    max-start: 0
    max-end: 1

  # Allow truthy values common in Kubernetes
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Allow long lines in comments for URLs and examples
  comments-indentation: disable

  # Require document separators for multi-document files
  document-start:
    present: true
    level: warning

  # Allow multiple documents in one file
  document-end: disable

  # Be strict about empty values in security contexts
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true

  # Prevent key duplicates (important for security)
  key-duplicates: enable

  # Allow octal values (common in file permissions)
  octal-values:
    forbid-implicit-octal: false
    forbid-explicit-octal: false

  # Be more strict about quoted strings
  quoted-strings:
    quote-type: any
    required: only-when-needed

  # Allow braces
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Allow brackets
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Strict colons
  colons:
    max-spaces-after: 1
    level: error

  # Strict commas
  commas:
    max-spaces-after: 1
    level: error

  # Strict hyphens
  hyphens:
    level: error

  # Require new line at end of file
  new-line-at-end-of-file: enable

  # Disallow trailing spaces
  trailing-spaces: enable

  # Allow key ordering flexibility
  key-ordering: disable

  # Be strict with line endings for consistency
  new-lines:
    type: unix
    level: error

ignore: |
  .git/
  .github/
  node_modules/
  *.md
  credentials/
  security-reports/
  .secrets/ 