# YugabyteDB Multi-Cluster Override File for codet-staging-yb
# Environment: staging
# Region: us-central1, Zone: us-central1-b

isMultiAz: false
AZ: us-central1-b

# Single-cluster master addresses (fixing DNS issue)
masterAddresses: "yb-master-0.yb-masters.codet-staging-yb.svc.cluster.local:7100"

# Storage configuration
storage:
  master:
    storageClass: "standard-rwo"
    size: "200Gi"
  tserver:
    storageClass: "standard-rwo"
    size: "200Gi"

# Replica configuration
replicas:
  master: 1
  tserver: 1
  totalMasters: 1

# Resource configuration
resource:
  master:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1500m"
      memory: "3Gi"
  tserver:
    requests:
      cpu: "2000m"
      memory: "4Gi"
    limits:
      cpu: "2500m"
      memory: "6Gi"

# Global flags for multi-cluster setup
gflags:
  master:
    placement_cloud: "gke"
    placement_region: "us-central1"
    placement_zone: "us-central1-b"
    leader_failure_max_missed_heartbeat_periods: 10
    raft_heartbeat_interval_ms: 1000
    enable_ysql: true
    default_memory_limit_to_ram_ratio: 0.85
  tserver:
    placement_cloud: "gke"
    placement_region: "us-central1"
    placement_zone: "us-central1-b"
    leader_failure_max_missed_heartbeat_periods: 10
    raft_heartbeat_interval_ms: 1000
    enable_ysql: true
    default_memory_limit_to_ram_ratio: 0.85
    # CDC configuration
    cdc_max_stream_intent_records: 10000

# Security configuration
auth:
  enabled: false
  useSecretFile: false

tls:
  enabled: false
  nodeToNode: false
  clientToServer: false

# Service configuration
services:
  master:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
  tserver:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
  yb-master-ui:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
  yb-tserver-service:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
  yugabyted-ui-service:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"

# Pod configuration
pod:
  master:
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
    tolerations:
      - key: "environment"
        operator: "Equal"
        value: "staging"
        effect: "NoSchedule"
    nodeSelector:
      environment: "staging"
    annotations:
      cluster.name: "codet-staging-yb"
      environment: "staging"
  tserver:
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
    tolerations:
      - key: "environment"
        operator: "Equal"
        value: "staging"
        effect: "NoSchedule"
    nodeSelector:
      environment: "staging"
    annotations:
      cluster.name: "codet-staging-yb"
      environment: "staging"

# Network policy
networkPolicy:
  enabled: true

# Monitoring
serviceMonitor:
  enabled: false

# Environment-specific configurations

# Staging specific settings  
# domainName: codet-staging-yb.local  # Removed - causing DNS issues
image:
  tag: "2.25.2"
