# YugabyteDB Multi-Cluster Override File for codet-prod-yb
# Environment: prod
# Region: us-east1, Zone: us-east1-b

isMultiAz: false
AZ: us-east1-b

# Single-cluster master addresses (fixing DNS issue)
masterAddresses: "yb-master-0.yb-masters.codet-prod-yb.svc.cluster.local:7100"

# Storage configuration
storage:
  master:
    storageClass: "standard-rwo"
    size: "500Gi"
  tserver:
    storageClass: "standard-rwo"
    size: "500Gi"

# Replica configuration
replicas:
  master: 1
  tserver: 1
  totalMasters: 1

# Resource configuration
resource:
  master:
    requests:
      cpu: "2000m"
      memory: "4Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  tserver:
    requests:
      cpu: "4000m"
      memory: "8Gi"
    limits:
      cpu: "4000m"
      memory: "8Gi"

# Global flags for multi-cluster setup
gflags:
  master:
    placement_cloud: "gke"
    placement_region: "us-east1"
    placement_zone: "us-east1-b"
    leader_failure_max_missed_heartbeat_periods: 10
    raft_heartbeat_interval_ms: 1000
    enable_ysql: true
    default_memory_limit_to_ram_ratio: 0.85
  tserver:
    placement_cloud: "gke"
    placement_region: "us-east1"
    placement_zone: "us-east1-b"
    leader_failure_max_missed_heartbeat_periods: 10
    raft_heartbeat_interval_ms: 1000
    enable_ysql: true
    default_memory_limit_to_ram_ratio: 0.85
    # CDC configuration
    cdc_max_stream_intent_records: 10000

# Security configuration
auth:
  enabled: true
  useSecretFile: true

tls:
  enabled: true
  nodeToNode: true
  clientToServer: true

# Service configuration
services:
  master:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
  tserver:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
  yb-master-ui:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
  yb-tserver-service:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
  yugabyted-ui-service:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"

# Pod configuration
pod:
  master:
    tolerations:
      - key: "environment"
        operator: "Equal"
        value: "prod"
        effect: "NoSchedule"
    nodeSelector:
      environment: "prod"
    annotations:
      cluster.name: "codet-prod-yb"
      environment: "prod"
  tserver:
    tolerations:
      - key: "environment"
        operator: "Equal"
        value: "prod"
        effect: "NoSchedule"
    nodeSelector:
      environment: "prod"
    annotations:
      cluster.name: "codet-prod-yb"
      environment: "prod"

# Network policy
networkPolicy:
  enabled: true

# Monitoring
serviceMonitor:
  enabled: false

# Environment-specific configurations

# Production specific settings
# domainName: codet-prod-yb.local  # Removed - causing DNS issues
image:
  tag: "2.25.2"

# Production backup configuration
backups:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: "30d"
