# YugabyteDB Multi-Cluster Override File for codet-dev-yb
# Environment: dev
# Region: us-west1, Zone: us-west1-b

isMultiAz: false
AZ: us-west1-b

# Single-cluster master addresses (fixing DNS issue)
masterAddresses: "yb-master-0.yb-masters.codet-dev-yb.svc.cluster.local:7100"

# Storage configuration
storage:
  master:
    storageClass: "standard-rwo"
    size: "100Gi"
  tserver:
    storageClass: "standard-rwo"
    size: "100Gi"

# Replica configuration
replicas:
  master: 1
  tserver: 1
  totalMasters: 1

# Resource configuration
resource:
  master:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  tserver:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

# Global flags for multi-cluster setup
gflags:
  master:
    placement_cloud: "gke"
    placement_region: "us-west1"
    placement_zone: "us-west1-b"
    leader_failure_max_missed_heartbeat_periods: 10
    raft_heartbeat_interval_ms: 1000
    enable_ysql: true
    default_memory_limit_to_ram_ratio: 0.85
  tserver:
    placement_cloud: "gke"
    placement_region: "us-west1"
    placement_zone: "us-west1-b"
    leader_failure_max_missed_heartbeat_periods: 10
    raft_heartbeat_interval_ms: 1000
    enable_ysql: true
    default_memory_limit_to_ram_ratio: 0.85
    # CDC configuration
    cdc_max_stream_intent_records: 10000

# Security configuration
auth:
  enabled: false
  useSecretFile: false

tls:
  enabled: false
  nodeToNode: false
  clientToServer: false

# Service configuration
services:
  master:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
  tserver:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
  yb-master-ui:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
  yb-tserver-service:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"
  yugabyted-ui-service:
    type: LoadBalancer
    annotations:
      cloud.google.com/load-balancer-type: "External"
    loadBalancerSourceRanges:
      - "0.0.0.0/0"

# Pod configuration
pod:
  master:
    tolerations:
      - key: "environment"
        operator: "Equal"
        value: "dev"
        effect: "NoSchedule"
    nodeSelector:
      environment: "dev"
    annotations:
      cluster.name: "codet-dev-yb"
      environment: "dev"
  tserver:
    tolerations:
      - key: "environment"
        operator: "Equal"
        value: "dev"
        effect: "NoSchedule"
    nodeSelector:
      environment: "dev"
    annotations:
      cluster.name: "codet-dev-yb"
      environment: "dev"

# Network policy
networkPolicy:
  enabled: true

# Monitoring
serviceMonitor:
  enabled: false

# Environment-specific configurations

# Development specific settings
# domainName: codet-dev-yb.local  # Removed - causing DNS issues
image:
  tag: "2.25.2-b0"
