# External Secrets Operator Setup for YugabyteDB Multi-Cluster
# This addresses CRITICAL security issue: Empty password fields in secrets

# DEPLOYMENT INSTRUCTIONS:
# 1. Install External Secrets Operator via Helm:
#    helm repo add external-secrets https://charts.external-secrets.io
#    helm install external-secrets external-secrets/external-secrets -n external-secrets-system --create-namespace
#
# 2. Set your PROJECT_ID environment variable or replace ${PROJECT_ID} below:
#    export PROJECT_ID="your-gcp-project-id"
#    envsubst < external-secrets-setup.yaml | kubectl apply -f -

---
# Service Account for External Secrets to access Google Secret Manager
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: external-secrets-system
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@${PROJECT_ID:-your-project-id}.iam.gserviceaccount.com

---
# ClusterSecretStore for Google Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm-secret-store
spec:
  provider:
    gcpsm:
      projectId: "${PROJECT_ID:-your-project-id}"
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: codet-staging-yb
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets-system

---
# Alternative ClusterSecretStore using service account key (for non-GKE environments)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm-secret-store-key
spec:
  provider:
    gcpsm:
      projectId: "${PROJECT_ID:-your-project-id}"
      auth:
        secretRef:
          secretAccessKey:
            name: gcpsm-secret
            key: secret-access-credentials
            namespace: external-secrets-system

---
# Secret containing GCP service account key (if using key-based auth)
# Create this secret with:
# kubectl create secret generic gcpsm-secret \
#   --from-file=secret-access-credentials=path/to/service-account-key.json \
#   --namespace external-secrets-system
apiVersion: v1
kind: Secret
metadata:
  name: gcpsm-secret
  namespace: external-secrets-system
type: Opaque
data:
  secret-access-credentials: ""  # Populated via kubectl command above

---
# ExternalSecret for Development Environment
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: codet-dev-yb-credentials
  namespace: codet-dev-yb
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: codet-dev-yb-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: yugabyte.password
    remoteRef:
      key: codet-dev-yugabyte-password
  - secretKey: postgres.password
    remoteRef:
      key: codet-dev-postgres-password
  refreshInterval: 1h

---
# ExternalSecret for Staging Environment
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: codet-staging-yb-credentials
  namespace: codet-staging-yb
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: codet-staging-yb-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: yugabyte.password
    remoteRef:
      key: codet-staging-yugabyte-password
  - secretKey: postgres.password
    remoteRef:
      key: codet-staging-postgres-password
  refreshInterval: 1h

---
# ExternalSecret for Production Environment
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: codet-prod-yb-credentials
  namespace: codet-prod-yb
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: codet-prod-yb-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: yugabyte.password
    remoteRef:
      key: codet-prod-yugabyte-password
  - secretKey: postgres.password
    remoteRef:
      key: codet-prod-postgres-password
  refreshInterval: 30m  # More frequent refresh for production

---
# ExternalSecret for Grafana Admin Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: admin-user
    remoteRef:
      key: grafana-admin-user
  - secretKey: admin-password
    remoteRef:
      key: grafana-admin-password
  refreshInterval: 1h

---
# ExternalSecret for SMTP Relay Configuration
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-credentials
  namespace: monitoring
spec:
  secretStoreRef:
    name: gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: smtp-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: username
    remoteRef:
      key: smtp-username
  - secretKey: password
    remoteRef:
      key: smtp-password
  refreshInterval: 24h

---
# Monitoring for External Secrets
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-secrets-metrics
  namespace: external-secrets-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics

---
# RBAC for External Secrets Operator
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets-controller
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "update", "delete", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["external-secrets.io"]
  resources: ["secretstores", "clustersecretstores", "externalsecrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-secrets-controller
subjects:
- kind: ServiceAccount
  name: external-secrets-sa
  namespace: external-secrets-system 