# Namespace Definitions for YugabyteDB Multi-Cluster Deployment
# Includes proper labels for network policies and security

---
# Development Environment Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: codet-dev-yb
  labels:
    name: codet-dev-yb
    environment: development
    cluster: codet-dev-yb
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Staging Environment Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: codet-staging-yb
  labels:
    name: codet-staging-yb
    environment: staging
    cluster: codet-staging-yb
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Production Environment Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: codet-prod-yb
  labels:
    name: codet-prod-yb
    environment: production
    cluster: codet-prod-yb
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Kafka/CDC Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    name: kafka
    environment: shared
    component: messaging
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Monitoring Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: shared
    component: observability
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Backup Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: backup
  labels:
    name: backup
    environment: shared
    component: backup
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted 