# YugabyteDB Production Cluster Configuration
# Environment: Production
# Cluster: Codet-Prod-YB
# Region: us-east1, Zone: us-east1-b

apiVersion: v1
kind: ConfigMap
metadata:
  name: codet-prod-yb-cluster-config
  namespace: codet-prod-yb
  labels:
    app: yugabytedb
    environment: prod
    cluster: codet-prod-yb
data:
  cluster.name: "codet-prod-yb"
  cluster.region: "us-east1"
  cluster.zone: "us-east1-b"
  cluster.environment: "prod"
  cluster.domain: "codet-prod-yb.local"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: codet-prod-yb-credentials
  namespace: codet-prod-yb
  labels:
    app: yugabytedb
    environment: prod
    cluster: codet-prod-yb
type: Opaque
data:
  # SECURITY: Passwords removed from version control - CRITICAL FOR PRODUCTION
  # Generate secrets using: make generate-secrets-prod
  # Or manually: kubectl create secret generic codet-prod-yb-credentials \
  #   --from-literal=yugabyte.password="$(openssl rand -base64 48)" \
  #   --from-literal=postgres.password="$(openssl rand -base64 48)" \
  #   --namespace=codet-prod-yb
  yugabyte.password: ""  # MUST be set via external secret management - NEVER COMMIT
  postgres.password: ""  # MUST be set via external secret management - NEVER COMMIT
  
---
# Enhanced Network Policy for Production Environment
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: codet-prod-yb-network-policy
  namespace: codet-prod-yb
  labels:
    app: yugabytedb
    environment: prod
    cluster: codet-prod-yb
spec:
  podSelector:
    matchLabels:
      app: yugabytedb
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Strict internal cluster communication
  - from:
    - namespaceSelector:
        matchLabels:
          name: codet-prod-yb
    - podSelector:
        matchLabels:
          app: yugabytedb
    ports:
    - protocol: TCP
      port: 7000   # Master Web UI (restricted)
    - protocol: TCP
      port: 7100   # Master RPC
    - protocol: TCP
      port: 9000   # TServer Web UI (restricted)
    - protocol: TCP
      port: 9100   # TServer RPC
    - protocol: TCP
      port: 5433   # YSQL
    - protocol: TCP
      port: 9042   # YCQL
    - protocol: TCP
      port: 6379   # YEDIS
  # Limited access from dev and staging for multi-cluster communication
  - from:
    - namespaceSelector:
        matchLabels:
          name: codet-dev-yb
    - namespaceSelector:
        matchLabels:
          name: codet-staging-yb
    ports:
    - protocol: TCP
      port: 7100   # Master RPC for multi-cluster only
    - protocol: TCP
      port: 9100   # TServer RPC for multi-cluster only
  egress:
  # Allow outbound to other YugabyteDB clusters (controlled)
  - to:
    - namespaceSelector:
        matchLabels:
          name: codet-dev-yb
    - namespaceSelector:
        matchLabels:
          name: codet-staging-yb
    ports:
    - protocol: TCP
      port: 7100
    - protocol: TCP
      port: 9100
  # Allow DNS
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS for downloads and updates (restricted)
  - to: []
    ports:
    - protocol: TCP
      port: 443

---
# Service Account for Production YugabyteDB
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codet-prod-yb-service-account
  namespace: codet-prod-yb
  labels:
    app: yugabytedb
    environment: prod
    cluster: codet-prod-yb
automountServiceAccountToken: true

---
# Enhanced Role for Production YugabyteDB
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: codet-prod-yb-role
  namespace: codet-prod-yb
  labels:
    app: yugabytedb
    environment: prod
    cluster: codet-prod-yb
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]  # More restrictive for secrets in production
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# RoleBinding for Production YugabyteDB
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codet-prod-yb-rolebinding
  namespace: codet-prod-yb
  labels:
    app: yugabytedb
    environment: prod
    cluster: codet-prod-yb
subjects:
- kind: ServiceAccount
  name: codet-prod-yb-service-account
  namespace: codet-prod-yb
roleRef:
  kind: Role
  name: codet-prod-yb-role
  apiGroup: rbac.authorization.k8s.io

---
# Enhanced Pod Disruption Budget for Production
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-prod-yb-master-pdb
  namespace: codet-prod-yb
  labels:
    app: yugabytedb
    component: master
    environment: prod
    cluster: codet-prod-yb
spec:
  minAvailable: 2  # Higher availability for production
  selector:
    matchLabels:
      app: yb-master

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-prod-yb-tserver-pdb
  namespace: codet-prod-yb
  labels:
    app: yugabytedb
    component: tserver
    environment: prod
    cluster: codet-prod-yb
spec:
  minAvailable: 2  # Higher availability for production
  selector:
    matchLabels:
      app: yb-tserver

---
# Production Backup Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: codet-prod-yb-backup-config
  namespace: codet-prod-yb
  labels:
    app: yugabytedb
    component: backup
    environment: prod
    cluster: codet-prod-yb
data:
  backup-schedule: "0 2 * * *"  # Daily at 2 AM
  backup-retention: "30d"
  backup-location: "gs://codet-prod-yb-backups"
  backup-encryption: "true"

---
# Production Pod Security Standards Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: codet-prod-yb-security-config
  namespace: codet-prod-yb
  labels:
    app: yugabytedb
    environment: prod
    cluster: codet-prod-yb
data:
  security.policy: "restricted"
  security.runAsNonRoot: "true"
  security.runAsUser: "1000"
  security.runAsGroup: "1000"
  security.fsGroup: "1000"
  security.allowPrivilegeEscalation: "false"
  security.readOnlyRootFilesystem: "true"
  security.dropCapabilities: "ALL" 