# YugabyteDB Staging Cluster Configuration
# Environment: Staging
# Cluster: Codet-Staging-YB
# Region: us-central1, Zone: us-central1-b

apiVersion: v1
kind: ConfigMap
metadata:
  name: codet-staging-yb-cluster-config
  namespace: codet-staging-yb
  labels:
    app: yugabytedb
    environment: staging
    cluster: codet-staging-yb
data:
  cluster.name: "codet-staging-yb"
  cluster.region: "us-central1"
  cluster.zone: "us-central1-b"
  cluster.environment: "staging"
  cluster.domain: "codet-staging-yb.local"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: codet-staging-yb-credentials
  namespace: codet-staging-yb
  labels:
    app: yugabytedb
    environment: staging
    cluster: codet-staging-yb
type: Opaque
data:
  # SECURITY: Passwords removed from version control
  # Generate secrets using: make generate-secrets-staging
  # Or manually: kubectl create secret generic codet-staging-yb-credentials \
  #   --from-literal=yugabyte.password="$(openssl rand -base64 32)" \
  #   --from-literal=postgres.password="$(openssl rand -base64 32)" \
  #   --namespace=codet-staging-yb
  yugabyte.password: ""  # Set via external secret management - DO NOT COMMIT PASSWORDS
  postgres.password: ""  # Set via external secret management - DO NOT COMMIT PASSWORDS
  
---
# Network Policy for Staging Environment
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: codet-staging-yb-network-policy
  namespace: codet-staging-yb
  labels:
    app: yugabytedb
    environment: staging
    cluster: codet-staging-yb
spec:
  podSelector:
    matchLabels:
      app: yugabytedb
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow internal cluster communication
  - from:
    - namespaceSelector:
        matchLabels:
          name: codet-staging-yb
    ports:
    - protocol: TCP
      port: 7000   # Master Web UI
    - protocol: TCP
      port: 7100   # Master RPC
    - protocol: TCP
      port: 9000   # TServer Web UI
    - protocol: TCP
      port: 9100   # TServer RPC
    - protocol: TCP
      port: 5433   # YSQL
    - protocol: TCP
      port: 9042   # YCQL
    - protocol: TCP
      port: 6379   # YEDIS
  # Allow from dev and prod for multi-cluster communication
  - from:
    - namespaceSelector:
        matchLabels:
          name: codet-dev-yb
    - namespaceSelector:
        matchLabels:
          name: codet-prod-yb
    ports:
    - protocol: TCP
      port: 7100   # Master RPC for multi-cluster
    - protocol: TCP
      port: 9100   # TServer RPC for multi-cluster
  egress:
  # Allow outbound to other YugabyteDB clusters
  - to:
    - namespaceSelector:
        matchLabels:
          name: codet-dev-yb
    - namespaceSelector:
        matchLabels:
          name: codet-prod-yb
    ports:
    - protocol: TCP
      port: 7100
    - protocol: TCP
      port: 9100
  # Allow DNS
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS for downloads and updates
  - to: []
    ports:
    - protocol: TCP
      port: 443

---
# Service Account for Staging YugabyteDB
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codet-staging-yb-service-account
  namespace: codet-staging-yb
  labels:
    app: yugabytedb
    environment: staging
    cluster: codet-staging-yb
automountServiceAccountToken: true

---
# Role for Staging YugabyteDB
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: codet-staging-yb-role
  namespace: codet-staging-yb
  labels:
    app: yugabytedb
    environment: staging
    cluster: codet-staging-yb
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# RoleBinding for Staging YugabyteDB
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codet-staging-yb-rolebinding
  namespace: codet-staging-yb
  labels:
    app: yugabytedb
    environment: staging
    cluster: codet-staging-yb
subjects:
- kind: ServiceAccount
  name: codet-staging-yb-service-account
  namespace: codet-staging-yb
roleRef:
  kind: Role
  name: codet-staging-yb-role
  apiGroup: rbac.authorization.k8s.io

---
# Pod Disruption Budget for Staging
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-staging-yb-master-pdb
  namespace: codet-staging-yb
  labels:
    app: yugabytedb
    component: master
    environment: staging
    cluster: codet-staging-yb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: yb-master

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-staging-yb-tserver-pdb
  namespace: codet-staging-yb
  labels:
    app: yugabytedb
    component: tserver
    environment: staging
    cluster: codet-staging-yb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: yb-tserver 