apiVersion: yugabytedb.yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: codet-staging-yb
  namespace: codet-staging-yb
  labels:
    environment: staging
    app: yugabytedb
    cost: minimal
spec:
  image:
    repository: yugabytedb/yugabyte
    tag: 2.20.2.0-b98  # Use same stable version as production
  # MINIMAL: Single replication for staging cost savings
  replicationFactor: 1  # Reduced from 3 for cost

  # Domain for the cluster
  domain: cluster.local

  # Master Node Configuration (minimal staging)
  master:
    replicas: 1  # Reduced from 3 for cost savings
    storage:
      size: 10Gi  # Reduced from 20Gi
      storageClass: pd-standard  # Changed from standard-rwo for better consistency
    resources:
      requests:
        cpu: "0.5"      # Reduced significantly
        memory: 1Gi     # Reduced from 3Gi
      limits:
        cpu: "1"        # Reduced from 2
        memory: 2Gi     # Reduced from 4Gi
    # Simplified affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-standard-2
              - e2-standard-4
    # Enable security in staging for production consistency
    enableAuth: true   # Changed from false - enable auth for security consistency
    tls:
      enabled: true    # Changed from false - enable TLS for security consistency

  # T-Server Node Configuration (minimal staging)
  tserver:
    replicas: 1  # Reduced from 3 for single node setup
    storage:
      size: 20Gi  # Reduced from 100Gi
      storageClass: pd-standard  # Changed from standard-rwo for better consistency
    resources:
      requests:
        cpu: "1"        # Consistent baseline
        memory: 2Gi     # Consistent baseline
      limits:
        cpu: "2"        # Increased from 1 for proper headroom
        memory: 4Gi     # Increased from 3Gi for proper headroom
    # Add tolerations for dedicated tserver nodes
    tolerations:
    - key: "yugabyte.com/tserver"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    # Simplified affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-standard-2
        # Prefer tserver nodes if available
        - weight: 80
          preference:
            matchExpressions:
            - key: node-pool
              operator: In
              values:
              - yugabyte-tserver
    # Enable security in staging for production consistency
    enableAuth: true   # Changed from false - enable auth for security consistency
    tls:
      enabled: true    # Changed from false - enable TLS for security consistency

  # Enable monitoring for staging visibility
  monitoring:
    enabled: true      # Changed from false - enable monitoring for staging visibility

  # Minimal resource quotas
  resourceQuota:
    enabled: true
    hard:
      requests.cpu: "3"      # Low limits
      requests.memory: "6Gi"
      persistentvolumeclaims: "3" 