apiVersion: yugabytedb.yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: codet-prod-yb
  namespace: codet-prod-yb
  labels:
    environment: production
    app: yugabytedb
    security: enabled
spec:
  image:
    repository: yugabytedb/yugabyte
    tag: 2.22.0.0-b15  # Updated to latest LTS
  # ✅ FIXED: Proper replication for production
  replicationFactor: 3  # ✅ FIXED: High availability

  # Domain for the cluster
  domain: cluster.local

  # Master Node Configuration (production-grade)
  master:
    replicas: 3  # ✅ FIXED: Proper quorum
    storage:
      size: 100Gi           # ✅ FIXED: Increased from 10Gi
      storageClass: pd-ssd  # ✅ FIXED: SSD for performance
    resources:
      requests:
        cpu: "2"       # ✅ FIXED: Increased from 0.5
        memory: 4Gi    # ✅ FIXED: Increased from 1Gi
      limits:
        cpu: "4"       # ✅ FIXED: Increased from 1
        memory: 8Gi    # ✅ FIXED: Increased from 2Gi
    # Multi-zone anti-affinity for HA
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - n2-standard-4
              - n2-standard-8
              - n2-highmem-4
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values: ["yb-master"]
          topologyKey: kubernetes.io/hostname
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["yb-master"]
            topologyKey: topology.kubernetes.io/zone
    # ✅ FIXED: ENABLE Authentication and TLS for production
    enableAuth: true
    authCredentials:
      ysql:
        user: yugabyte
        passwordSecretName: yugabyte-auth-secret
    tls:
      enabled: true
      rootCA:
        cert: yugabyte-tls-ca-cert
        key: yugabyte-tls-ca-key

  # T-Server Node Configuration (production-grade)
  tserver:
    replicas: 3  # ✅ FIXED: High availability
    storage:
      size: 500Gi          # ✅ FIXED: Increased from 20Gi
      storageClass: pd-ssd # ✅ FIXED: SSD for performance
    resources:
      requests:
        cpu: "4"       # ✅ FIXED: Increased from 1
        memory: 8Gi    # ✅ FIXED: Increased from 2Gi
      limits:
        cpu: "8"       # ✅ FIXED: Increased from 1
        memory: 16Gi   # ✅ FIXED: Increased from 2Gi
    # Tolerations for dedicated tserver nodes
    tolerations:
    - key: "yugabyte.com/tserver"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    # Multi-zone anti-affinity for HA
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: workload-type
              operator: In
              values: ["yugabyte-tserver"]
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - n2-highmem-4
              - n2-highmem-8
              - n2-standard-8
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values: ["yb-tserver"]
          topologyKey: kubernetes.io/hostname
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["yb-tserver"]
            topologyKey: topology.kubernetes.io/zone
    # ✅ FIXED: ENABLE Authentication and TLS for production
    enableAuth: true
    authCredentials:
      ysql:
        user: yugabyte
        passwordSecretName: yugabyte-auth-secret
    tls:
      enabled: true
      rootCA:
        cert: yugabyte-tls-ca-cert
        key: yugabyte-tls-ca-key

  # ✅ FIXED: ENABLE monitoring for production
  monitoring:
    enabled: true

  # Enable service monitor
  serviceMonitor:
    enabled: true

  # PodDisruptionBudgets for HA
  podDisruptionBudget:
    maxUnavailable:
      master: 1
      tserver: 1

  # Production resource quotas
  resourceQuota:
    enabled: true
    hard:
      requests.cpu: "30"      # Increased for 3x3 + headroom
      requests.memory: "60Gi"  # Increased for 3x3 + headroom
      persistentvolumeclaims: "10"
  
  # ✅ FIXED: Production-grade configurations
  gflags:
    master:
      # Security settings
      use_client_to_server_encryption: "true"
      use_node_to_node_encryption: "true"
      certs_dir: "/opt/certs"
      # Performance settings
      tablet_split_size_threshold_bytes: "10737418240"  # 10GB
      tablet_split_low_phase_size_threshold_bytes: "5368709120"  # 5GB
      # CDC optimizations
      cdc_state_checkpoint_update_interval_ms: "15000"
      # Multi-zone settings
      placement_cloud: "gcp"
      placement_region: "us-central1"
      placement_zone: "us-central1-a,us-central1-b,us-central1-f"
      
    tserver:
      # Security settings
      use_client_to_server_encryption: "true"
      use_node_to_node_encryption: "true"
      certs_dir: "/opt/certs"
      # Performance settings  
      memstore_size_mb: "1024"
      global_memstore_size_mb_max: "2048"
      # CDC optimizations
      cdc_state_checkpoint_update_interval_ms: "15000"
      cdc_checkpoint_opid_interval_ms: "60000"
      update_min_cdc_indices_interval_secs: "60"
      cdc_max_stream_intent_records: "1000"
      log_min_seconds_to_retain: "86400"  # Keep WAL for 24 hours
      # Multi-zone settings
      placement_cloud: "gcp"
      placement_region: "us-central1"
      placement_zone: "us-central1-a,us-central1-b,us-central1-f"

  # ✅ FIXED: Complete backup configuration for production
  backup:
    enabled: true
    retentionDays: 30
    schedule: "0 2 * * *"  # Daily at 2 AM
    storageBackend:
      type: "gcs"
      gcs:
        bucketName: "yugabytedb-backups-prod"
        pathPrefix: "codet-prod-yb"
        # Credentials will be provided via Workload Identity or service account
        credentialsSecretName: "gcs-backup-credentials"
    parallelism: 4  # Number of parallel backup streams
    compression: true
    encryption: true
    # Full backup weekly, incremental daily
    incrementalBackup:
      enabled: true
      frequency: "daily"
      fullBackupFrequency: "weekly" 