apiVersion: yugabytedb.yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: codet-staging-yb
  namespace: codet-staging-yb
  labels:
    environment: staging
    app: yugabytedb
    cost: minimal
spec:
  image:
    repository: yugabytedb/yugabyte
    tag: 2.20.2.0-b98  # Use same stable version as production
  # MINIMAL: Single replication for staging cost savings
  replicationFactor: 1  # Reduced from 3 for cost

  # Domain for the cluster
  domain: cluster.local

  # Master Node Configuration (minimal staging)
  master:
    replicas: 1  # Reduced from 3 for cost savings
    storage:
      size: 10Gi  # Reduced from 20Gi
      storageClass: standard-rwo
    resources:
      requests:
        cpu: "0.5"      # Reduced significantly
        memory: 1Gi     # Reduced from 3Gi
      limits:
        cpu: "1"        # Reduced from 2
        memory: 2Gi     # Reduced from 4Gi
    # Simplified affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-standard-2
              - e2-standard-4
    # Disable expensive features for cost savings
    enableAuth: false  # Disabled for minimal cost
    tls:
      enabled: false   # Disabled for minimal cost

  # T-Server Node Configuration (minimal staging)
  tserver:
    replicas: 1  # Reduced from 3 for single node setup
    storage:
      size: 20Gi  # Reduced from 100Gi
      storageClass: standard-rwo
    resources:
      requests:
        cpu: "1"        # Reduced from 3-4
        memory: 2Gi     # Reduced from 6-8Gi
      limits:
        cpu: "1"        # Reduced from 4
        memory: 3Gi     # Reduced from 8Gi
    # Simplified affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-standard-2
    # Disable expensive features for cost savings
    enableAuth: false  # Disabled for minimal cost
    tls:
      enabled: false   # Disabled for minimal cost

  # Disable monitoring for cost savings
  monitoring:
    enabled: false  # Disabled for cost savings

  # Minimal resource quotas
  resourceQuota:
    enabled: true
    hard:
      requests.cpu: "3"      # Low limits
      requests.memory: "6Gi"
      persistentvolumeclaims: "3" 