apiVersion: yugabytedb.yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: codet-dev-yb
  namespace: codet-dev-yb
  labels:
    environment: development
    app: yugabytedb
    cost: minimal
spec:
  image:
    repository: yugabytedb/yugabyte
    tag: 2.20.2.0-b98  # Use same stable version as production
  # MINIMAL: Single replication for development cost savings
  replicationFactor: 1  # Reduced from 3 for cost

  # Domain for the cluster
  domain: cluster.local

  # Master Node Configuration (minimal dev)
  master:
    replicas: 1  # Reduced from 3 for cost savings
    storage:
      size: 20Gi  # Increased for better dev experience
      storageClass: pd-ssd  # Consistent with production for testing
    resources:
      requests:
        cpu: "1"        # Increased for stability
        memory: 2Gi     # Increased for stability
      limits:
        cpu: "2"        # Increased limit
        memory: 4Gi     # Increased limit
    # Simplified affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-micro
              - e2-small
    # DISABLED: Authentication and TLS for cost savings
    enableAuth: false
    tls:
      enabled: false

  # T-Server Node Configuration (minimal dev)
  tserver:
    replicas: 1  # Reduced from 3 for single node setup
    storage:
      size: 50Gi  # Increased for better dev experience
      storageClass: pd-ssd  # Consistent with production for testing
    resources:
      requests:
        cpu: "2"        # Increased for database workload
        memory: 4Gi     # Increased for database workload
      limits:
        cpu: "4"        # Increased limit for better performance
        memory: 8Gi     # Increased limit for database operations
    # Add tolerations for dedicated tserver nodes
    tolerations:
    - key: "yugabyte.com/tserver"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    # Simplified affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-micro
              - e2-small
        # Prefer tserver nodes if available
        - weight: 80
          preference:
            matchExpressions:
            - key: node-pool
              operator: In
              values:
              - yugabyte-tserver
    # DISABLED: Authentication and TLS for cost savings
    enableAuth: false
    tls:
      enabled: false

  # DISABLED: monitoring for cost savings
  monitoring:
    enabled: false

  # Disable service monitor
  serviceMonitor:
    enabled: false

  # Updated resource quotas
  resourceQuota:
    enabled: true
    hard:
      requests.cpu: "6"      # Increased to match new allocations (1+2+buffer)
      requests.memory: "12Gi" # Increased to match new allocations (2+4+buffer)
      persistentvolumeclaims: "6" 