apiVersion: yugabytedb.yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: codet-dev-yb
  namespace: codet-dev-yb
  labels:
    environment: development
    app: yugabytedb
    cost: minimal
spec:
  image:
    repository: yugabytedb/yugabyte
    tag: 2.20.2.0-b98  # Use same stable version as production
  # MINIMAL: Reduced replication for cost savings
  replicationFactor: 1  # Reduced from 3 for dev environment

  # Domain for the cluster
  domain: cluster.local

  # Master Node Configuration (minimal resources)
  master:
    replicas: 1  # Reduced from 3 for cost savings
    storage:
      size: 5Gi  # Reduced from 10Gi
      storageClass: pd-standard  # Changed from standard-rwo for better consistency
    resources:
      requests:
        cpu: "0.5"      # Consistent with limits
        memory: 1Gi     # Consistent with limits
      limits:
        cpu: "1"        # Increased from 0.5 for headroom
        memory: 2Gi     # Increased from 1Gi for headroom
    # Simplified affinity for single replica
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-standard-2
              - e2-micro
    # Enable security even in dev for consistency and testing
    enableAuth: true   # Changed from false - enable auth for security consistency
    tls:
      enabled: true    # Changed from false - enable TLS for security consistency

  # T-Server Node Configuration (minimal resources)
  tserver:
    replicas: 1  # Reduced from 3 for single node setup
    storage:
      size: 10Gi  # Reduced from 50Gi
      storageClass: pd-standard  # Changed from standard-rwo for better consistency
    resources:
      requests:
        cpu: "0.5"      # Reduced from 2
        memory: 2Gi     # Reduced from 4Gi
      limits:
        cpu: "1"        # Reduced from 2
        memory: 2Gi     # Reduced from 4Gi
    # Add tolerations for dedicated tserver nodes
    tolerations:
    - key: "yugabyte.com/tserver"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    # Simplified affinity for single replica
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-standard-2
              - e2-standard-4
        # Prefer tserver nodes if available
        - weight: 80
          preference:
            matchExpressions:
            - key: node-pool
              operator: In
              values:
              - yugabyte-tserver
    # Enable security even in dev for consistency and testing
    enableAuth: true   # Changed from false - enable auth for security consistency
    tls:
      enabled: true    # Changed from false - enable TLS for security consistency

  # Enable monitoring for visibility into dev environment
  monitoring:
    enabled: true      # Changed from false - enable monitoring for dev visibility

  # Minimal resource quotas
  resourceQuota:
    enabled: true
    hard:
      requests.cpu: "2"      # Very low limits
      requests.memory: "4Gi"
      persistentvolumeclaims: "3" 