apiVersion: yugabytedb.yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: codet-prod-yb
  namespace: codet-prod-yb
  labels:
    environment: production
    app: yugabytedb
    cost: minimal
spec:
  image:
    repository: yugabytedb/yugabyte
    tag: latest
  # Minimal replication even for production (cost over reliability)
  replicationFactor: 1  # Reduced from 3 for extreme cost savings

  # Domain for the cluster
  domain: cluster.local

  # Master Node Configuration (minimal production)
  master:
    replicas: 1  # Reduced from 3 for cost savings
    storage:
      size: 20Gi  # Reduced from 50Gi
      storageClass: standard-rwo  # Use standard instead of SSD
    resources:
      requests:
        cpu: "1"        # Reduced from 2-3
        memory: 2Gi     # Reduced from 4-6Gi
      limits:
        cpu: "1"        # Reduced from 3
        memory: 2Gi     # Reduced from 6Gi
    # Simplified affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-standard-2
    # Keep some security but disable TLS for cost
    enableAuth: true   # Keep auth for production
    tls:
      enabled: false   # Disabled for cost savings
    # Remove expensive annotations
    podAnnotations: {}

  # T-Server Node Configuration (minimal production)
  tserver:
    replicas: 1  # Reduced from 5 for extreme cost savings
    storage:
      size: 50Gi  # Reduced from 500Gi
      storageClass: standard-rwo  # Use standard instead of SSD
    resources:
      requests:
        cpu: "1"        # Reduced from 4-6
        memory: 4Gi     # Reduced from 8-12Gi
      limits:
        cpu: "2"        # Reduced from 6
        memory: 4Gi     # Reduced from 12Gi
    # Simplified affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-standard-2
    # Keep some security but disable TLS for cost
    enableAuth: true   # Keep auth for production
    tls:
      enabled: false   # Disabled for cost savings
    # Remove expensive annotations
    podAnnotations: {}

  # Disable monitoring for cost savings
  monitoring:
    enabled: false  # Disabled for cost savings

  # Remove service monitor
  serviceMonitor:
    enabled: false

  # Minimal resource quotas
  resourceQuota:
    enabled: true
    hard:
      requests.cpu: "4"       # Much lower than original 30
      requests.memory: "8Gi"  # Much lower than original 60Gi
      persistentvolumeclaims: "3"  # Reduced from 10 