apiVersion: yugabytedb.yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: codet-dev-yb
  namespace: codet-dev-yb
  labels:
    environment: development
    app: yugabytedb
    cost: minimal
spec:
  image:
    repository: yugabytedb/yugabyte
    tag: 2.20.2.0-b98  # Use same stable version as production
  # MINIMAL: Single replication for development cost savings
  replicationFactor: 1  # Reduced from 3 for cost

  # Domain for the cluster
  domain: cluster.local

  # Master Node Configuration (minimal dev)
  master:
    replicas: 1  # Reduced from 3 for cost savings
    storage:
      size: 10Gi  # Reduced from 20Gi
      storageClass: pd-standard  # Changed from standard-rwo for cost
    resources:
      requests:
        cpu: "0.5"      # Minimal CPU
        memory: 1Gi     # Minimal memory
      limits:
        cpu: "1"        # Low limit
        memory: 2Gi     # Low limit
    # Simplified affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-micro
              - e2-small
    # DISABLED: Authentication and TLS for cost savings
    enableAuth: false
    tls:
      enabled: false

  # T-Server Node Configuration (minimal dev)
  tserver:
    replicas: 1  # Reduced from 3 for single node setup
    storage:
      size: 20Gi  # Reduced from 100Gi
      storageClass: pd-standard  # Changed for cost optimization
    resources:
      requests:
        cpu: "1"        # Consistent baseline
        memory: 2Gi     # Reduced memory
      limits:
        cpu: "1"        # Reduced for cost
        memory: 2Gi     # Reduced for cost
    # Add tolerations for dedicated tserver nodes
    tolerations:
    - key: "yugabyte.com/tserver"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    # Simplified affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-micro
              - e2-small
        # Prefer tserver nodes if available
        - weight: 80
          preference:
            matchExpressions:
            - key: node-pool
              operator: In
              values:
              - yugabyte-tserver
    # DISABLED: Authentication and TLS for cost savings
    enableAuth: false
    tls:
      enabled: false

  # DISABLED: monitoring for cost savings
  monitoring:
    enabled: false

  # Disable service monitor
  serviceMonitor:
    enabled: false

  # Minimal resource quotas
  resourceQuota:
    enabled: true
    hard:
      requests.cpu: "3"      # Low limits
      requests.memory: "4Gi" # Reduced memory quota
      persistentvolumeclaims: "3" 