apiVersion: yugabytedb.yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: codet-prod-yb
  namespace: codet-prod-yb
  labels:
    environment: production
    app: yugabytedb
    cost: minimal
spec:
  image:
    repository: yugabytedb/yugabyte
    tag: 2.20.2.0-b98
  # MINIMAL: Single replication for cost savings
  replicationFactor: 1

  # Domain for the cluster
  domain: cluster.local

  # Master Node Configuration (minimal cost)
  master:
    replicas: 1
    storage:
      size: 10Gi
      storageClass: pd-standard
    resources:
      requests:
        cpu: "0.5"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi
    # Simplified affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-micro
              - e2-small
    # DISABLED: Authentication and TLS for cost savings
    enableAuth: false
    tls:
      enabled: false

  # T-Server Node Configuration (minimal cost)
  tserver:
    replicas: 1
    storage:
      size: 20Gi
      storageClass: pd-standard
    resources:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        cpu: "1"
        memory: 2Gi
    # Add tolerations for dedicated tserver nodes
    tolerations:
    - key: "yugabyte.com/tserver"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    # Simplified affinity
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-micro
              - e2-small
        # Prefer tserver nodes if available
        - weight: 80
          preference:
            matchExpressions:
            - key: node-pool
              operator: In
              values:
              - yugabyte-tserver
    # DISABLED: Authentication and TLS for cost savings
    enableAuth: false
    tls:
      enabled: false

  # DISABLED: monitoring for cost savings
  monitoring:
    enabled: false

  # Disable service monitor
  serviceMonitor:
    enabled: false

  # Minimal resource quotas
  resourceQuota:
    enabled: true
    hard:
      requests.cpu: "3"
      requests.memory: "4Gi"
      persistentvolumeclaims: "3"
  
  # Minimal configurations
  gflags:
    master:
      # Minimal performance settings
      tablet_split_size_threshold_bytes: "1073741824"
      tablet_split_low_phase_size_threshold_bytes: "536870912"
      # Disabled security for cost
      use_client_to_server_encryption: "false"
      use_node_to_node_encryption: "false"
    tserver:
      # Minimal performance settings  
      memstore_size_mb: "256"
      global_memstore_size_mb_max: "512"
      # Disabled security for cost
      use_client_to_server_encryption: "false"
      use_node_to_node_encryption: "false"

  # DISABLED: Backup for cost savings
  backup:
    enabled: false 