apiVersion: yugabytedb.yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: codet-dev-yb
  namespace: codet-dev-yb
  labels:
    environment: development
    app: yugabytedb
    cost: minimal
spec:
  image:
    repository: yugabytedb/yugabyte
    tag: latest
  # MINIMAL: Reduced replication for cost savings
  replicationFactor: 1  # Reduced from 3 for dev environment

  # Domain for the cluster
  domain: cluster.local

  # Master Node Configuration (minimal resources)
  master:
    replicas: 1  # Reduced from 3 for cost savings
    storage:
      size: 5Gi  # Reduced from 10Gi
      storageClass: standard-rwo
    resources:
      requests:
        cpu: "0.5"      # Reduced from 1
        memory: 1Gi     # Reduced from 2Gi
      limits:
        cpu: "0.5"      # Reduced from 1
        memory: 1Gi     # Reduced from 2Gi
    # Simplified affinity for single replica
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-micro
              - e2-small
    # Disable expensive features for cost savings
    enableAuth: false  # Disabled for minimal cost
    tls:
      enabled: false   # Disabled for minimal cost

  # T-Server Node Configuration (minimal resources)
  tserver:
    replicas: 1  # Reduced from 3 for single node setup
    storage:
      size: 10Gi  # Reduced from 50Gi
      storageClass: standard-rwo
    resources:
      requests:
        cpu: "0.5"      # Reduced from 2
        memory: 2Gi     # Reduced from 4Gi
      limits:
        cpu: "1"        # Reduced from 2
        memory: 2Gi     # Reduced from 4Gi
    # Simplified affinity for single replica
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-standard-2
              - e2-standard-4
    # Disable expensive features for cost savings
    enableAuth: false  # Disabled for minimal cost
    tls:
      enabled: false   # Disabled for minimal cost

  # Disable monitoring for cost savings
  monitoring:
    enabled: false  # Disabled for cost savings

  # Minimal resource quotas
  resourceQuota:
    enabled: true
    hard:
      requests.cpu: "2"      # Very low limits
      requests.memory: "4Gi"
      persistentvolumeclaims: "3" 