apiVersion: yugabytedb.yugabyte.com/v1alpha1
kind: YBCluster
metadata:
  name: codet-prod-yb
  namespace: codet-prod-yb
  labels:
    environment: production
    app: yugabytedb
    cost: optimized
spec:
  image:
    repository: yugabytedb/yugabyte
    tag: 2.20.2.0-b98
  # PRODUCTION: Enable proper replication for high availability
  replicationFactor: 3

  # Domain for the cluster
  domain: cluster.local

  # Master Node Configuration (production-ready)
  master:
    replicas: 3
    storage:
      size: 50Gi
      storageClass: pd-ssd
    resources:
      requests:
        cpu: "2"
        memory: 4Gi
      limits:
        cpu: "2"
        memory: 4Gi
    # Production anti-affinity for HA
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - yb-master
          topologyKey: kubernetes.io/hostname
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-standard-2
              - e2-standard-4
    # PRODUCTION SECURITY: Enable full security
    enableAuth: true
    tls:
      enabled: true
    # Production annotations for monitoring
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "7000"

  # T-Server Node Configuration (production-ready)
  tserver:
    replicas: 3
    storage:
      size: 200Gi
      storageClass: pd-ssd
    resources:
      requests:
        cpu: "2"
        memory: 8Gi
      limits:
        cpu: "4"
        memory: 8Gi
    # Add tolerations for dedicated tserver nodes
    tolerations:
    - key: "yugabyte.com/tserver"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    # Production anti-affinity for HA
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - yb-tserver
          topologyKey: kubernetes.io/hostname
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: node.kubernetes.io/instance-type
              operator: In
              values:
              - e2-standard-2
              - e2-standard-4
        # Prefer tserver nodes if available
        - weight: 80
          preference:
            matchExpressions:
            - key: node-pool
              operator: In
              values:
              - yugabyte-tserver
    # PRODUCTION SECURITY: Enable full security
    enableAuth: true
    tls:
      enabled: true
    # Production annotations for monitoring
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9000"

  # ENABLE monitoring for production
  monitoring:
    enabled: true

  # Enable service monitor for Prometheus
  serviceMonitor:
    enabled: true

  # Production resource quotas
  resourceQuota:
    enabled: true
    hard:
      requests.cpu: "15"
      requests.memory: "36Gi"
      persistentvolumeclaims: "10"
  
  # Production-specific configurations
  gflags:
    master:
      # Production performance optimizations
      tablet_split_size_threshold_bytes: "10737418240"
      tablet_split_low_phase_size_threshold_bytes: "5368709120"
      # Security settings
      use_client_to_server_encryption: "true"
      use_node_to_node_encryption: "true"
    tserver:
      # Production performance optimizations  
      memstore_size_mb: "1024"
      global_memstore_size_mb_max: "2048"
      # Security settings
      use_client_to_server_encryption: "true"
      use_node_to_node_encryption: "true"

  # Backup configuration for production
  backup:
    enabled: true
    schedule: "0 2 * * *"
    retention: "7d" 