---
# GCS Backup Credentials Secret Template
# This secret provides access credentials for YugabyteDB backups to Google Cloud Storage
apiVersion: v1
kind: Secret
metadata:
  name: gcs-backup-credentials
  namespace: codet-prod-yb
  labels:
    app: yugabytedb
    component: backup
    environment: production
type: Opaque
stringData:
  # Option 1: Service Account Key (JSON format)
  # Use this when Workload Identity is not available
  # gcs-service-account-key.json: |
  #   {
  #     "type": "service_account",
  #     "project_id": "your-project-id",
  #     "private_key_id": "key-id",
  #     "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
  #     "client_email": "yugabytedb-backup@your-project-id.iam.gserviceaccount.com",
  #     "client_id": "client-id",
  #     "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  #     "token_uri": "https://oauth2.googleapis.com/token",
  #     "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  #     "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/yugabytedb-backup%40your-project-id.iam.gserviceaccount.com"
  #   }
  
  # Option 2: Access credentials (when using Workload Identity)
  # This file will be generated by the setup script
  credentials: ""

---
# Production Backup Configuration
# This ConfigMap contains backup-specific configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: codet-prod-yb
  labels:
    app: yugabytedb
    component: backup
    environment: production
data:
  # GCS bucket configuration
  bucket-name: "yugabytedb-backups-prod"
  bucket-region: "us-central1"
  path-prefix: "codet-prod-yb"
  
  # Backup retention policies
  retention-days: "30"
  long-term-retention-days: "365"  # Keep yearly backups for 1 year
  
  # Backup scheduling
  full-backup-schedule: "0 2 * * 0"  # Sundays at 2 AM
  incremental-backup-schedule: "0 2 * * 1-6"  # Monday-Saturday at 2 AM
  
  # Performance settings
  backup-parallelism: "4"
  compression-enabled: "true"
  encryption-enabled: "true"
  
  # Backup verification
  verify-backups: "true"
  verification-schedule: "0 6 * * 1"  # Verify backups every Monday at 6 AM 