# Database Secrets Template
# Replace {ENVIRONMENT} with actual environment (dev, staging, prod)
# Replace {BASE64_PASSWORD} with base64 encoded passwords

apiVersion: v1
kind: Secret
metadata:
  name: codet-{ENVIRONMENT}-db-credentials
  namespace: codet-{ENVIRONMENT}-yb
  labels:
    app: yugabytedb
    environment: {ENVIRONMENT}
type: Opaque
data:
  # Base64 encoded passwords
  admin-password: {BASE64_ADMIN_PASSWORD}
  app-password: {BASE64_APP_PASSWORD}
  yugabyte-password: e3VnYWJ5dGU=  # default 'yugabyte' for initial setup
stringData:
  # Plain text for reference - these will be automatically base64 encoded
  admin-username: codet_{ENVIRONMENT}_admin
  app-username: codet_{ENVIRONMENT}_app
  database-name: codet_{ENVIRONMENT}
  host: codet-{ENVIRONMENT}-yb-yb-tserver-service.codet-{ENVIRONMENT}-yb.svc.cluster.local
  port: "5433" 