# YugabyteDB Development Environment Values
# Optimized for smooth performance while cost-conscious + CDC enabled

image:
  repository: yugabytedb/yugabyte
  tag: "2024.2.3.1-b3"

# Single replication for development cost savings
replicas:
  master: 1
  tserver: 1

# Disable load balancer for cost savings initially
enableLoadBalancer: false

# Minimal but working resource configuration
resource:
  master:
    requests:
      cpu: "0.5"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  tserver:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

# Storage configuration - using standard PDs
storage:
  master:
    count: 1
    size: "10Gi"
    storageClass: "pd-standard"
  tserver:
    count: 1
    size: "20Gi"
    storageClass: "pd-standard"

# SECURITY WARNING: Auth disabled for development only
# ENABLE in production!
auth:
  enabled: false

tls:
  enabled: false

# Monitoring disabled for cost optimization
istio:
  enabled: false

# Disable unnecessary features for cost optimization + CDC optimizations
gflags:
  master:
    max_clock_skew_usec: 200000
    default_memory_limit_to_ram_ratio: 0.85
    # CDC-specific flags
    cdc_state_checkpoint_update_interval_ms: 15000
    
  tserver:
    max_clock_skew_usec: 200000
    # FIXED: Removed conflicting memory_limit_hard_bytes
    default_memory_limit_to_ram_ratio: 0.85
    # CDC-specific optimizations
    cdc_state_checkpoint_update_interval_ms: 15000
    cdc_checkpoint_opid_interval_ms: 60000
    update_min_cdc_indices_interval_secs: 60
    cdc_max_stream_intent_records: 1000
    log_min_seconds_to_retain: 3600  # Keep WAL for 1 hour for CDC

# Pod disruption budget settings
podDisruptionBudget:
  maxUnavailable: 1

# Network policy disabled for simplicity
networkPolicy:
  enabled: false

# Service configuration - expose CDC ports
service:
  enabled: true
  type: ClusterIP
  ports:
    # Standard YugabyteDB ports
    ysql: 5433
    ycql: 9042
    yb-master-ui: 7000
    # CDC-specific ports
    cdc-service: 8080

# Annotations for cost optimization
annotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

# Enable monitoring for performance tracking
yugabytedUi:
  enabled: true 