# YugabyteDB Development Environment Values
# Cost-optimized configuration for development

image:
  repository: yugabytedb/yugabyte
  tag: "2.20.2.0-b98"

# MINIMAL: Single replication for development cost savings
replicas:
  master: 1
  tserver: 1

# Disable load balancer for cost savings
enableLoadBalancer: false

# Master configuration - VERY minimal for small cluster
resource:
  master:
    requests:
      cpu: "0.2"
      memory: "512Mi"
    limits:
      cpu: "0.5"
      memory: "1Gi"
  tserver:
    requests:
      cpu: "0.2"
      memory: "512Mi"
    limits:
      cpu: "0.5"
      memory: "1Gi"

# Storage configuration - smaller sizes
storage:
  master:
    size: "5Gi"
    storageClass: "pd-standard"
  tserver:
    size: "10Gi"
    storageClass: "pd-standard"

# DISABLED: Authentication and TLS for cost savings
auth:
  enabled: false

tls:
  enabled: false

# DISABLED: monitoring for cost savings
prometheus:
  enabled: false

serviceMonitor:
  enabled: false

# Remove node selector and tolerations for simple scheduling
nodeSelector: {}

# Remove complex affinity rules
affinity: {}

# Remove tserver tolerations that might prevent scheduling
tolerations: {}

# Labels
labels:
  environment: development
  app: yugabytedb
  cost: minimal

# Disable istio
istio:
  enabled: false

# Disable partition tolerance for single node setup
partition_tolerance: false 