# YugabyteDB Helm Production Values
# Based on comprehensive end-to-end plan for 99.95% availability

replicaCount:
  master: 3       # one per AZ for quorum
  tserver: 5      # uneven spreads to handle 2 node loss

resource:
  master:
    requests: 
      cpu: 500m 
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 4Gi
  tserver:
    requests: 
      cpu: "1" 
      memory: 4Gi
    limits:
      cpu: "4"
      memory: 8Gi

placement:
  cloud: gcp
  region: us-central1
  zones:
    - us-central1-a
    - us-central1-b
    - us-central1-c

storage:
  master:
    count: 1
    size: 100Gi
    storageClass: pd-ssd-regional
  tserver:
    count: 1
    size: 500Gi
    storageClass: pd-ssd-regional

# Performance and CDC optimizations
masterGFlags:
  enable_ysql: "true"
  ysql_enable_auth: "true"
  enable_automatic_tablet_splitting: "true"
  tablet_split_low_phase_size_threshold_bytes: "536870912"   # 512 MB
  tablet_split_high_phase_size_threshold_bytes: "10737418240" # 10 GB
  cdc_state_checkpoint_update_interval_ms: "15000"
  placement_cloud: "gcp"
  placement_region: "us-central1"
  use_client_to_server_encryption: "true"
  use_node_to_node_encryption: "true"

tserverGFlags:
  enable_ysql: "true"
  ysql_enable_auth: "true"
  enable_automatic_tablet_splitting: "true"
  tablet_split_low_phase_size_threshold_bytes: "536870912"   # 512 MB
  tablet_split_high_phase_size_threshold_bytes: "10737418240" # 10 GB
  memstore_size_mb: "1024"
  global_memstore_size_mb_max: "2048"
  cdc_state_checkpoint_update_interval_ms: "15000"
  cdc_checkpoint_opid_interval_ms: "60000"
  update_min_cdc_indices_interval_secs: "60"
  cdc_max_stream_intent_records: "1000"
  log_min_seconds_to_retain: "86400"  # Keep WAL for 24 hours
  placement_cloud: "gcp"
  placement_region: "us-central1"
  use_client_to_server_encryption: "true"
  use_node_to_node_encryption: "true"

# RBAC and Security
rbac:
  create: true

tls:
  enabled: true
  nodeToNode: true
  clientToServer: true

auth:
  enabled: true

# Monitoring and Observability
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9300"

# High Availability
pdb:
  master: 
    maxUnavailable: 1
  tserver: 
    maxUnavailable: 1

# Anti-affinity for fault tolerance
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          component: yb-master
      topologyKey: "kubernetes.io/hostname"
    - labelSelector:
        matchLabels:
          component: yb-tserver  
      topologyKey: "kubernetes.io/hostname"
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            component: yb-master
        topologyKey: "topology.kubernetes.io/zone"
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            component: yb-tserver
        topologyKey: "topology.kubernetes.io/zone"

# Service configuration
services:
  master:
    type: ClusterIP
  tserver:
    type: ClusterIP

# Image configuration
image:
  repository: yugabytedb/yugabyte
  tag: "2024.1.2.0-b77"
  pullPolicy: IfNotPresent

# Node tolerations for dedicated pools
tolerations:
  tserver:
    - key: "yugabyte.com/tserver"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

# Volume permissions and security
securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true 