# YugabyteDB Production Environment Values
# SECURE configuration for production

image:
  repository: yugabytedb/yugabyte
  tag: "2.20.2.0-b98"

# HIGH AVAILABILITY: Increase replication for production
replicas:
  master: 3    # ✅ FIXED: Proper quorum
  tserver: 3   # ✅ FIXED: High availability

# Enable load balancer for production
enableLoadBalancer: true

# PRODUCTION RESOURCES: Proper allocation
resource:
  master:
    requests:
      cpu: "2"       # ✅ FIXED: Increased from 0.5
      memory: "4Gi"  # ✅ FIXED: Increased from 1Gi
    limits:
      cpu: "4"       # ✅ FIXED: Increased from 1
      memory: "8Gi"  # ✅ FIXED: Increased from 2Gi
  tserver:
    requests:
      cpu: "4"       # ✅ FIXED: Increased from 1
      memory: "8Gi"  # ✅ FIXED: Increased from 2Gi
    limits:
      cpu: "8"       # ✅ FIXED: Increased from 1
      memory: "16Gi" # ✅ FIXED: Increased from 2Gi

# PRODUCTION STORAGE: SSD for performance
storage:
  master:
    size: "100Gi"           # ✅ FIXED: Increased from 10Gi
    storageClass: "pd-ssd"  # ✅ FIXED: SSD for performance
  tserver:
    size: "500Gi"           # ✅ FIXED: Increased from 20Gi
    storageClass: "pd-ssd"  # ✅ FIXED: SSD for performance

# ✅ FIXED: ENABLE Authentication for production
auth:
  enabled: true
  useSecretFile: true

# ✅ FIXED: ENABLE TLS for production
tls:
  enabled: true
  certManager:
    enabled: true

# ✅ FIXED: ENABLE monitoring for production
prometheus:
  enabled: true

serviceMonitor:
  enabled: true

# Node affinity for production workloads
nodeSelector: {}

affinity:
  master:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
            - n2-standard-4    # ✅ FIXED: Better machine types
            - n2-standard-8
            - n2-highmem-4
  tserver:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
            - n2-standard-8    # ✅ FIXED: Better machine types
            - n2-highmem-8
            - n2-highmem-16
      - weight: 80
        preference:
          matchExpressions:
          - key: node-pool
            operator: In
            values:
            - yugabyte-tserver

# Add tolerations for dedicated tserver nodes
tolerations:
  tserver:
  - key: "yugabyte.com/tserver"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

# ✅ FIXED: Enable security features
rbac:
  create: true

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 10001

# ✅ FIXED: Enable network policies
networkPolicy:
  enabled: true

# ✅ FIXED: Enable backup for production
backup:
  enabled: true
  retentionDays: 30
  schedule: "0 2 * * *"  # Daily at 2 AM

# ✅ FIXED: Production-grade gflags
gflags:
  master:
    # Security flags
    use_client_to_server_encryption: "true"
    use_node_to_node_encryption: "true"
    certs_dir: "/opt/certs"
    # Performance flags
    tablet_split_size_threshold_bytes: "10737418240"  # 10GB
    tablet_split_low_phase_size_threshold_bytes: "5368709120"  # 5GB
    # CDC optimizations
    cdc_state_checkpoint_update_interval_ms: 15000
    
  tserver:
    # Security flags
    use_client_to_server_encryption: "true"
    use_node_to_node_encryption: "true"
    certs_dir: "/opt/certs"
    # Performance flags  
    memstore_size_mb: "1024"
    global_memstore_size_mb_max: "2048"
    # CDC optimizations
    cdc_state_checkpoint_update_interval_ms: 15000
    cdc_checkpoint_opid_interval_ms: 60000
    update_min_cdc_indices_interval_secs: 60
    cdc_max_stream_intent_records: 1000
    log_min_seconds_to_retain: 86400  # Keep WAL for 24 hours

# Labels
labels:
  environment: production
  app: yugabytedb
  security: enabled
  backup: enabled 