# YugabyteDB Staging Environment Values
# Production-like configuration for staging with security enabled

image:
  repository: yugabytedb/yugabyte
  tag: "2.20.2.0-b98"

# IMPROVED: Better replication for staging reliability
replicas:
  master: 3    # ✅ FIXED: Proper quorum for testing
  tserver: 3   # ✅ FIXED: Multi-node testing

# Enable load balancer for staging
enableLoadBalancer: true

# IMPROVED RESOURCES: Better than dev, less than prod
resource:
  master:
    requests:
      cpu: "1"       # ✅ FIXED: Increased from 0.5
      memory: "2Gi"  # ✅ FIXED: Increased from 1Gi
    limits:
      cpu: "2"       # ✅ FIXED: Increased from 1
      memory: "4Gi"  # ✅ FIXED: Increased from 2Gi
  tserver:
    requests:
      cpu: "2"       # ✅ FIXED: Increased from 1
      memory: "4Gi"  # ✅ FIXED: Increased from 2Gi
    limits:
      cpu: "4"       # ✅ FIXED: Increased from 1
      memory: "8Gi"  # ✅ FIXED: Increased from 2Gi

# IMPROVED STORAGE: Better storage for staging
storage:
  master:
    size: "50Gi"            # ✅ FIXED: Increased from 10Gi
    storageClass: "pd-ssd"  # ✅ FIXED: SSD for better performance
  tserver:
    size: "200Gi"           # ✅ FIXED: Increased from 20Gi
    storageClass: "pd-ssd"  # ✅ FIXED: SSD for better performance

# ✅ FIXED: ENABLE Authentication for staging (production-like)
auth:
  enabled: true
  useSecretFile: true

# ✅ FIXED: ENABLE TLS for staging (production-like)
tls:
  enabled: true
  certManager:
    enabled: true

# ✅ FIXED: ENABLE monitoring for staging
prometheus:
  enabled: true

serviceMonitor:
  enabled: true

# Node affinity for staging workloads
nodeSelector: {}

affinity:
  master:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
            - n2-standard-2    # ✅ FIXED: Better machine types
            - n2-standard-4
  tserver:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
            - n2-standard-4    # ✅ FIXED: Better machine types
            - n2-highmem-4
      - weight: 80
        preference:
          matchExpressions:
          - key: node-pool
            operator: In
            values:
            - yugabyte-tserver

# Add tolerations for dedicated tserver nodes
tolerations:
  tserver:
  - key: "yugabyte.com/tserver"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

# ✅ FIXED: Enable security features
rbac:
  create: true

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 10001

# ✅ FIXED: Enable network policies
networkPolicy:
  enabled: true

# ✅ FIXED: Enable backup for staging
backup:
  enabled: true
  retentionDays: 7
  schedule: "0 3 * * *"  # Daily at 3 AM

# ✅ FIXED: Staging-appropriate gflags
gflags:
  master:
    # Security flags
    use_client_to_server_encryption: "true"
    use_node_to_node_encryption: "true"
    certs_dir: "/opt/certs"
    # Performance flags
    tablet_split_size_threshold_bytes: "5368709120"  # 5GB
    tablet_split_low_phase_size_threshold_bytes: "2684354560"  # 2.5GB
    # CDC optimizations
    cdc_state_checkpoint_update_interval_ms: 15000
    
  tserver:
    # Security flags
    use_client_to_server_encryption: "true"
    use_node_to_node_encryption: "true"
    certs_dir: "/opt/certs"
    # Performance flags  
    memstore_size_mb: "512"
    global_memstore_size_mb_max: "1024"
    # CDC optimizations
    cdc_state_checkpoint_update_interval_ms: 15000
    cdc_checkpoint_opid_interval_ms: 60000
    update_min_cdc_indices_interval_secs: 60
    cdc_max_stream_intent_records: 1000
    log_min_seconds_to_retain: 43200  # Keep WAL for 12 hours

# Labels
labels:
  environment: staging
  app: yugabytedb
  security: enabled
  backup: enabled 