# Network Policies for YugabyteDB Environments
# This file implements network segmentation and security between environments

---
# Default deny-all policy for dev environment
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: codet-dev-yb
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
# Allow YugabyteDB internal communication in dev
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: yugabytedb-internal
  namespace: codet-dev-yb
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values: ["yb-master", "yb-tserver"]
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow YugabyteDB pods to communicate with each other
  - from:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values: ["yb-master", "yb-tserver"]
    ports:
    - protocol: TCP
      port: 7000  # Master web UI
    - protocol: TCP
      port: 7100  # Master RPC
    - protocol: TCP
      port: 9000  # TServer web UI
    - protocol: TCP
      port: 9100  # TServer RPC
    - protocol: TCP
      port: 5433  # PostgreSQL
    - protocol: TCP
      port: 9042  # Cassandra
  # Allow monitoring access
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 7000
    - protocol: TCP
      port: 9000
  egress:
  # Allow YugabyteDB pods to communicate with each other
  - to:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values: ["yb-master", "yb-tserver"]
    ports:
    - protocol: TCP
      port: 7000
    - protocol: TCP
      port: 7100
    - protocol: TCP
      port: 9000
    - protocol: TCP
      port: 9100
  # Allow DNS
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

---
# Default deny-all policy for staging environment
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: codet-staging-yb
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
# Allow YugabyteDB internal communication in staging
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: yugabytedb-internal
  namespace: codet-staging-yb
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values: ["yb-master", "yb-tserver"]
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow YugabyteDB pods to communicate with each other
  - from:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values: ["yb-master", "yb-tserver"]
    ports:
    - protocol: TCP
      port: 7000
    - protocol: TCP
      port: 7100
    - protocol: TCP
      port: 9000
    - protocol: TCP
      port: 9100
    - protocol: TCP
      port: 5433
    - protocol: TCP
      port: 9042
  # Allow monitoring access
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 7000
    - protocol: TCP
      port: 9000
  egress:
  # Allow YugabyteDB pods to communicate with each other
  - to:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values: ["yb-master", "yb-tserver"]
    ports:
    - protocol: TCP
      port: 7000
    - protocol: TCP
      port: 7100
    - protocol: TCP
      port: 9000
    - protocol: TCP
      port: 9100
  # Allow DNS
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

---
# Default deny-all policy for production environment
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all
  namespace: codet-prod-yb
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
# Allow YugabyteDB internal communication in production
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: yugabytedb-internal
  namespace: codet-prod-yb
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values: ["yb-master", "yb-tserver"]
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow YugabyteDB pods to communicate with each other
  - from:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values: ["yb-master", "yb-tserver"]
    ports:
    - protocol: TCP
      port: 7000
    - protocol: TCP
      port: 7100
    - protocol: TCP
      port: 9000
    - protocol: TCP
      port: 9100
    - protocol: TCP
      port: 5433
    - protocol: TCP
      port: 9042
  # Allow monitoring access
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 7000
    - protocol: TCP
      port: 9000
  egress:
  # Allow YugabyteDB pods to communicate with each other
  - to:
    - podSelector:
        matchExpressions:
        - key: app
          operator: In
          values: ["yb-master", "yb-tserver"]
    ports:
    - protocol: TCP
      port: 7000
    - protocol: TCP
      port: 7100
    - protocol: TCP
      port: 9000
    - protocol: TCP
      port: 9100
  # Allow DNS
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

---
# Allow monitoring namespace to access all YugabyteDB metrics
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: prometheus
  policyTypes:
  - Egress
  egress:
  # Allow monitoring to access YugabyteDB namespaces
  - to:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: ["codet-dev-yb", "codet-staging-yb", "codet-prod-yb"]
    ports:
    - protocol: TCP
      port: 7000
    - protocol: TCP
      port: 9000
  # Allow DNS
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53 