# Pod Disruption Budget for YugabyteDB Operator
# Ensures operator availability during node maintenance and upgrades

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yugabyte-operator-pdb
  namespace: yb-operator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: yugabyte-k8s-operator 