# Pod Disruption Budgets for YugabyteDB
# Ensures high availability during voluntary disruptions like rolling updates

---
# Development Environment - Minimal disruption budget (single replica)
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-dev-yb-master-pdb
  namespace: codet-dev-yb
spec:
  minAvailable: 1  # Keep at least 1 master available (we only have 1)
  selector:
    matchLabels:
      app: yb-master

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-dev-yb-tserver-pdb
  namespace: codet-dev-yb
spec:
  minAvailable: 1  # Keep at least 1 tserver available (we only have 1)
  selector:
    matchLabels:
      app: yb-tserver

---
# Staging Environment - Minimal disruption budget (single replica)
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-staging-yb-master-pdb
  namespace: codet-staging-yb
spec:
  minAvailable: 1  # Keep at least 1 master available (we only have 1)
  selector:
    matchLabels:
      app: yb-master

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-staging-yb-tserver-pdb
  namespace: codet-staging-yb
spec:
  minAvailable: 1  # Keep at least 1 tserver available (we only have 1)
  selector:
    matchLabels:
      app: yb-tserver

---
# Production Environment - High availability disruption budgets
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-prod-yb-master-pdb
  namespace: codet-prod-yb
spec:
  minAvailable: 2  # Keep at least 2 out of 3 masters available for quorum
  selector:
    matchLabels:
      app: yb-master

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-prod-yb-tserver-pdb
  namespace: codet-prod-yb
spec:
  minAvailable: 2  # Keep at least 2 out of 3 tservers available for replication
  selector:
    matchLabels:
      app: yb-tserver

---
# Monitoring PDB to prevent monitoring downtime
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus-pdb
  namespace: monitoring
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: prometheus

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grafana-pdb
  namespace: monitoring
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: grafana 