# Pod Disruption Budgets for YugabyteDB
# Minimal configuration for single replica setup (cost optimized)

---
# Development Environment - Minimal disruption budget (single replica)
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-dev-yb-master-pdb
  namespace: codet-dev-yb
spec:
  minAvailable: 1  # Keep at least 1 master available (we only have 1)
  selector:
    matchLabels:
      app: yb-master

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-dev-yb-tserver-pdb
  namespace: codet-dev-yb
spec:
  minAvailable: 1  # Keep at least 1 tserver available (we only have 1)
  selector:
    matchLabels:
      app: yb-tserver

---
# Staging Environment - Minimal disruption budget (single replica)
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-staging-yb-master-pdb
  namespace: codet-staging-yb
spec:
  minAvailable: 1  # Keep at least 1 master available (we only have 1)
  selector:
    matchLabels:
      app: yb-master

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-staging-yb-tserver-pdb
  namespace: codet-staging-yb
spec:
  minAvailable: 1  # Keep at least 1 tserver available (we only have 1)
  selector:
    matchLabels:
      app: yb-tserver

---
# Production Environment - Minimal disruption budget (single replica for cost)
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-prod-yb-master-pdb
  namespace: codet-prod-yb
spec:
  minAvailable: 1  # Keep at least 1 master available (we only have 1)
  selector:
    matchLabels:
      app: yb-master

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-prod-yb-tserver-pdb
  namespace: codet-prod-yb
spec:
  minAvailable: 1  # Keep at least 1 tserver available (we only have 1)
  selector:
    matchLabels:
      app: yb-tserver

# NOTE: Monitoring PDBs removed - monitoring is disabled for cost optimization 