# Pod Security Standards for YugabyteDB Deployment
# Implements restricted security policies following Kubernetes Pod Security Standards

---
# Development environment namespace
apiVersion: v1
kind: Namespace
metadata:
  name: codet-dev-yb
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Staging environment namespace
apiVersion: v1
kind: Namespace
metadata:
  name: codet-staging-yb
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Production environment namespace
apiVersion: v1
kind: Namespace
metadata:
  name: codet-prod-yb
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Backup namespace security
apiVersion: v1
kind: Namespace
metadata:
  name: backup
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Kafka namespace security  
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Monitoring namespace security
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

---
# Security Context Constraints (if using OpenShift)
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: yugabytedb-scc
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: []
defaultAddCapabilities: []
requiredDropCapabilities:
- ALL
fsGroup:
  type: RunAsAny
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret

---
# Pod Disruption Budget for Development Master
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yb-master-pdb
  namespace: codet-dev-yb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: yb-master

---
# Pod Disruption Budget for Development TServer
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yb-tserver-pdb
  namespace: codet-dev-yb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: yb-tserver

---
# Pod Disruption Budget for Staging Master
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yb-master-pdb
  namespace: codet-staging-yb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: yb-master

---
# Pod Disruption Budget for Staging TServer
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yb-tserver-pdb
  namespace: codet-staging-yb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: yb-tserver

---
# Pod Disruption Budget for Production Master
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yb-master-pdb
  namespace: codet-prod-yb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: yb-master

---
# Pod Disruption Budget for Production TServer
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yb-tserver-pdb
  namespace: codet-prod-yb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: yb-tserver 
