# Resource Governance and Security Policies for YugabyteDB Multi-Cluster
# Implements resource quotas, limits, network policies, and pod disruption budgets

---
# Development Environment Resource Quota (Permissive)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: codet-dev-yb-quota
  namespace: codet-dev-yb
spec:
  hard:
    requests.cpu: "8"      # 8 CPU cores
    requests.memory: 16Gi   # 16GB RAM
    limits.cpu: "16"       # 16 CPU cores max burst  
    limits.memory: 32Gi     # 32GB RAM max burst
    persistentvolumeclaims: "10"
    requests.storage: 1Ti   # 1TB storage
    services: "10"
    services.loadbalancers: "2"
    services.nodeports: "5"
    pods: "30"              # Up to 30 pods
    count/deployments.apps: "10"
    count/statefulsets.apps: "5"

---
# Production Environment Resource Quota (Strict)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: codet-prod-yb-quota
  namespace: codet-prod-yb
spec:
  hard:
    requests.cpu: "32"      # 32 CPU cores
    requests.memory: 64Gi   # 64GB RAM
    limits.cpu: "48"       # 48 CPU cores max burst
    limits.memory: 96Gi     # 96GB RAM max burst
    persistentvolumeclaims: "20"
    requests.storage: 5Ti   # 5TB storage
    services: "20"
    services.loadbalancers: "5"
    services.nodeports: "3"
    pods: "100"             # Up to 100 pods
    count/deployments.apps: "20"
    count/statefulsets.apps: "10"

---
# Development Environment Limit Ranges
apiVersion: v1
kind: LimitRange
metadata:
  name: codet-dev-yb-limits
  namespace: codet-dev-yb
spec:
  limits:
  - type: Container
    default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "200m"
      memory: "512Mi"
    min:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "4"
      memory: "8Gi"
  - type: PersistentVolumeClaim
    min:
      storage: "10Gi"
    max:
      storage: "1Ti"

---
# Production Environment Limit Ranges
apiVersion: v1
kind: LimitRange
metadata:
  name: codet-prod-yb-limits
  namespace: codet-prod-yb
spec:
  limits:
  - type: Container
    default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    min:
      cpu: "200m"
      memory: "256Mi"
    max:
      cpu: "8"
      memory: "16Gi"
  - type: PersistentVolumeClaim
    min:
      storage: "100Gi"
    max:
      storage: "2Ti"

---
# Development Environment Network Policy (Open)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: codet-dev-yb-netpol
  namespace: codet-dev-yb
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}  # Allow all ingress (development ease)
  egress:
  - {}  # Allow all egress (development ease)

---
# Production Environment Network Policy (Restrictive)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: codet-prod-yb-netpol
  namespace: codet-prod-yb
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: codet-prod-yb
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 7000  # Master web UI
    - protocol: TCP
      port: 7100  # Master RPC
    - protocol: TCP
      port: 9000  # TServer web UI
    - protocol: TCP
      port: 9100  # TServer RPC
    - protocol: TCP
      port: 5433  # YSQL
    - protocol: TCP
      port: 9042  # YCQL
    - protocol: TCP
      port: 6379  # YEDIS
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: codet-prod-yb
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - namespaceSelector:
        matchLabels:
          name: kube-system
  - to: []  # Allow external egress for updates/backups
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
    - protocol: UDP
      port: 53

---
# Production Environment Pod Disruption Budget for Masters
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-prod-yb-master-pdb
  namespace: codet-prod-yb
spec:
  minAvailable: 2  # Always keep 2 masters available
  selector:
    matchLabels:
      app: yb-master

---
# Production Environment Pod Disruption Budget for TServers
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: codet-prod-yb-tserver-pdb
  namespace: codet-prod-yb
spec:
  minAvailable: 2  # Always keep 2 tservers available
  selector:
    matchLabels:
      app: yb-tserver

---
# Storage Classes for different workload tiers
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-high-iops
  labels:
    governance: storage-control
    tier: high-performance
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: regional-pd
  zones: us-east1-b,us-east1-c,us-east1-d
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-capacity
  labels:
    governance: storage-control
    tier: capacity
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-monitoring
  labels:
    governance: storage-control
    tier: monitoring
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: none
allowVolumeExpansion: true
volumeBindingMode: Immediate 