# Resource Quotas for YugabyteDB Helm Deployments
# Prevents resource exhaustion and enforces environment-specific limits

---
# Development Environment Resource Quota (Single-Zone Helm)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resource-quota
  namespace: codet-dev-yb
spec:
  hard:
    # Compute resources
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    
    # Storage
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
    
    # Object counts
    pods: "10"
    services: "10"
    configmaps: "20"
    secrets: "20"

---
# Staging Environment Resource Quota (Single-Zone Helm)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-resource-quota
  namespace: codet-staging-yb
spec:
  hard:
    # Compute resources
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    
    # Storage
    requests.storage: 300Gi
    persistentvolumeclaims: "15"
    
    # Object counts
    pods: "15"
    services: "15"
    configmaps: "30"
    secrets: "30"

---
# Production Multi-Zone Resource Quota - Zone A
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-zone-a-quota
  namespace: codet-prod-yb
spec:
  hard:
    # Compute resources (per zone)
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    
    # Storage (per zone)
    requests.storage: 1Ti
    persistentvolumeclaims: "20"
    
    # Object counts
    pods: "20"
    services: "10"
    configmaps: "20"
    secrets: "20"

---
# Production Multi-Zone Resource Quota - Zone B
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-zone-b-quota
  namespace: codet-prod-yb
spec:
  hard:
    # Compute resources (per zone)
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    
    # Storage (per zone)
    requests.storage: 1Ti
    persistentvolumeclaims: "20"
    
    # Object counts
    pods: "20"
    services: "10"
    configmaps: "20"
    secrets: "20"

---
# Production Multi-Zone Resource Quota - Zone C
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-zone-c-quota
  namespace: codet-prod-yb
spec:
  hard:
    # Compute resources (per zone)
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    
    # Storage (per zone)
    requests.storage: 1Ti
    persistentvolumeclaims: "20"
    
    # Object counts
    pods: "20"
    services: "10"
    configmaps: "20"
    secrets: "20"

---
# Kafka Namespace Resource Quota (for CDC)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: kafka-resource-quota
  namespace: kafka
spec:
  hard:
    # Compute resources
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    
    # Storage
    requests.storage: 500Gi
    persistentvolumeclaims: "30"
    
    # Object counts
    pods: "30"
    services: "15"
    configmaps: "30"
    secrets: "30"

---
# Monitoring Namespace Resource Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-resource-quota
  namespace: monitoring
spec:
  hard:
    # Compute resources
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    
    # Storage
    requests.storage: 200Gi
    persistentvolumeclaims: "20"
    
    # Object counts
    pods: "50"
    services: "20"
    configmaps: "50"
    secrets: "30" 
